# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
jwtMiddlewareException:
  - namespace: "orch-gateway"
    names:
      - "harbor-oci"
      - "ma-gitea"
      - "app-service-proxy"
      - "app-service-proxy-src"
      - "vnc-proxy-app-resource-manager-websocket-server"
      - "traefik-boots-ca-certificate"
      - "common-log-query-rest-proxy"
      - "web-ui-root"
      - "web-ui-infra"
      - "svc-fleet-https"
      - "onboardingmgr-api-grpc-stream"
      - "cluster-connect-gateway-ws"
      - "cluster-connect-gateway-kubeapi"
      - "orch-platform-keycloak"
      - "amt-api-rps"  # Added to allow OpenDMT RPC-RPS traffic, which fails due to missing JWT token.
  - namespace: "orch-boots"
    names:
      - "tinkerbell-haproxy-ingress"
anyMiddlewareException:
  - namespace: "orch-gateway"
    names:
      - "orch-platform-grafana"
      - "orch-platform-vault"
      - "edgenode-observability-grafana"
      - "traefik-boots-ca-certificate"
      - "harbor-oci"
      - "svc-fleet-https"
      - "onboardingmgr-api-grpc-stream"
      - "cluster-connect-gateway-ws"
      - "cluster-connect-gateway-kubeapi"

# https://doc.traefik.io/traefik/migrate/v2-to-v3-details/#kubernetes-crds-api-group-traefikcontainous
traefikApiGroup: "traefik.io/v1alpha1"
