# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
name: Auto Approve & Merge
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions: {}
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto approve PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
        if: github.actor == github.actor == 'sys-orch' &&
          github.event.pull_request.base.ref == 'main-pass-validation'
        run: |
          echo "Approving PR #${PR_NUMBER} by ${ACTOR}"
          gh pr review "${PR_NUMBER}" --repo "${REPO}" --approve --body "Auto approved by sys-orch-github-approve bot"
  auto-merge:
    permissions:
      pull-requests: write
      contents: write
    name: Auto merge PR
    needs:
      - auto-approve
    runs-on: ubuntu-latest
    if: |
      github.actor == 'sys-orch' &&
      github.event.pull_request.base.ref == 'main-pass-validation'
    steps:
      - name: Auto merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
        run: |
          echo "Enabling auto-merge for PR #${PR_NUMBER} by ${ACTOR}"
          gh pr merge "${PR_NUMBER}" --repo "${REPO}" --auto --squash
